#!/usr/bin/env python3
"""Generate a self-contained AI prompt for decompiling a function.

Finds a simple unmatched function (or uses a specified one), gathers all
necessary context (assembly, dependencies, source file, types), and produces
a prompt that can be fed directly to an AI assistant.

Usage:
    python3 tools/gen_prompt.py                          # auto-select
    python3 tools/gen_prompt.py <function_name>          # specific function
    python3 tools/gen_prompt.py --module game --max-size 100
    python3 tools/gen_prompt.py <function_name> --output prompt.md
"""

import argparse
import json
import os
import re
import subprocess
import sys

# Add tools directory to path for imports
script_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, script_dir)

import decomp_helper
from decomp_helper import parse_symbols, parse_splits, find_file_for_address, extract_asm, extract_ghidra_decomp
import feedback_diff
from feedback_diff import run_objdiff, find_unit_for_symbol, get_symbol_data

ROOT_DIR = os.path.dirname(script_dir)
CONFIG_BASE = os.path.join(ROOT_DIR, "config/GYQE01")


# ---------------------------------------------------------------------------
# Prompt template sections (embedded so the tool is self-contained, no AI)
# ---------------------------------------------------------------------------

BACKGROUND = """\
This is a matching decompilation project for Mario Superstar Baseball (GameCube, GYQE01).
The goal is to write C code that, when compiled with Metrowerks CodeWarrior GC/1.3.2,
produces the exact same binary as the original game.

Target architecture: PowerPC (Gekko/Broadway).
Compiler: Metrowerks CodeWarrior for GameCube, version 1.3.2.
Language: C (not C++)."""

COMPILER_PATTERNS = """\
### Pointer Globals vs Array Globals
Two distinct assembly patterns appear for globals — they require different C code:

- `lis rN, SYM@ha` + `addi rDst, rN, SYM@l` → `rDst = &SYM` (symbol IS the data — array or struct in-place)
- `lis rN, SYM@ha` + `lwz  rDst, SYM@l(rN)` → `rDst = *SYM` (symbol CONTAINS a pointer — dereference it)

If the assembly uses `lwz` with `@l`, the symbol is a **pointer global**: its first field (offset 0x0)
is a pointer to the actual data array. You must go through that field:
```c
// WRONG (addi pattern — symbol is the array):
elem = &sym[arg0];

// CORRECT (lwz pattern — symbol holds a pointer at offset 0):
elem = &sym.ptr_field[arg0];
```
The `⚠ POINTER-GLOBAL` warning in Referenced Symbols flags this case. When you see it,
field offsets listed belong to the **pointed-to element type**, not to the declared type of `sym`.

### Global Address Re-loading
The compiler re-loads the base address of a global variable (using `lis`/`addi`) even if
already in a register. Creating a local pointer (`Type* p = &g_Global;`) causes the
compiler to hold the address in one register, which mismatches the original. Use direct
global access (`g_Global.field = ...;`) in distinct logical blocks instead.

### Structure Assignments and Update-Form Instructions
The binary uses "load/store with update" instructions (`lfsu`, `stfsu`). These are
generated by structure-level assignments (`dst.pos = src.pos;`), NOT by individual field
copies (`dst.x = src.x; dst.z = src.z;`).

### Register Steering ("Anchoring") — Last Resort Only
Registers `r31`/`r30` are typically used for major object base pointers. Define a local
pointer at the exact line where assembly first allocates the base register. Defining it
at the top of the function causes the compiler to use a different register.
**Do NOT reach for register steering on the first attempt.** Write the simplest correct C
first. Only use `register` keywords or carefully ordered variable initializations if a
clean version fails to match after at least one build+diff cycle.

### ROData Ordering
Float constants are stored in `.rodata` in the order first encountered in C code. If
your code references `1.0f` before `0.0f` but the original did the reverse, rodata
labels will mismatch. Order your constant references to match the assembly.

### Loop Simplicity: for vs do-while
CW often optimizes `for (i = 0; i < N; i++)` into a bottom-test loop (`cmpwi`/`blt` at
the bottom of the loop body) when it can prove the loop body executes at least once (e.g.
when N is a compile-time constant > 0). **Start with a simple `for` loop even when the
assembly shows a bottom-branching `do { } while` pattern.** Only switch to an explicit
`do { } while` if the `for` loop fails to match after a clean attempt.
Similarly, don't manually replicate the assembly's stride arithmetic with separate loop
variables — use clean array indexing (`arr[i]`) and let the compiler generate the strides.

### Casting and Sign Extension
Use explicit casts to match `extsh` (sign-extend halfword) and `extsb` (sign-extend byte).
Ensure `lwz` vs `lhz` vs `lbz` matches your struct field types (u32 vs u16 vs u8).

### Float Expression Scheduling (fmuls / fmsubs)
For float expressions of the form `A*B - C*D`, CW generates:
```
fmuls dest, C, D          ; compute subtracted term first
fmsubs dest, A, B, dest   ; A*B - (C*D)
```
CW interleaves `lfs` loads naturally with the float ops when expressions are written
directly. **Do NOT pre-load struct fields into local float variables before the
expression.** Write inline:
```c
dest->x = vec1->y * vec2->z - vec1->z * vec2->y;  // CORRECT
```
NOT:
```c
f32 y1 = vec1->y, z1 = vec1->z, y2 = vec2->y, z2 = vec2->z;
dest->x = y1 * z2 - z1 * y2;  // WRONG — pre-loading disrupts scheduling
```
This applies to all float arithmetic: cross products, dot products, linear
interpolations, etc. Start with clean direct expressions; only introduce a temp
if the diff shows a specific register issue that the temp would fix.

### C89 Variable Declarations
The compiler (Metrowerks CodeWarrior) is extremely strict about C89 rules.
CRITICAL: You MUST declare ALL variables at the very BEGINNING of a block (`{ ... }`), before any other code or statements (like `if`, `memcpy`, or assignments).
Failure to do this will cause an "expression syntax error".
INCORRECT:
```c
void func() {
    int a;
    a = 5;
    int b; // SYNTAX ERROR: declaration after assignment
}
```
CORRECT:
```c
void func() {
    int a;
    int b; // Both at top
    a = 5;
}
```

### M2C_ERROR Means Missing Parameter
When m2c outputs `M2C_ERROR(/* Read from unset register $rX */)`, it means register rX
held an input value that m2c did not account for — i.e., the function has an additional
parameter passed in rX. The calling convention passes parameters in r3, r4, r5, r6, ...
in order. If you see `$r4` unset, the function has at least 2 parameters. If you see
`$r5`, it has at least 3, etc. Add the missing parameter(s) to the function signature.
Example: `M2C_ERROR(/* Read from unset register $r4 */)` → add `int arg1` as second param.

### Non-Void Return Type Detection
If the assembly contains `mr rSAVED, r3` immediately after a `bl` call (saving the
return value of the called function to a callee-saved register like r31 or r30), AND
`mr r3, rSAVED` appears just before `blr` (restoring it as the return value), then the
OUTER function is non-void — it returns the result of the inner call. Check the callee's
full prototype to determine the return type, and declare the outer function accordingly.
Example pattern:
```
bl  sndFXStartEx      ; returns SND_VOICEID
...
mr  r31, r3           ; save return value
bl  sndFXCtrl
...
mr  r3, r31           ; return the saved value
blr
```
→ outer function returns `SND_VOICEID`.

### Integer Offset vs. Pointer for Cross-Call Index Variables
When the same array index (e.g. `arg0 * 2`) must survive across a function call AND
the array's base address is a known global, use an INTEGER offset variable, NOT a
pointer variable:
```c
// CORRECT: saves only the int in r31; reloads global base each time
int off = arg0 * 2;
u8 a = ((u8*)&globalTable + off)[-0x2a2];
sndFXStartEx(..., a, ...);
u8 b = ((u8*)&globalTable + off)[-0x2a1];
```
```c
// WRONG: saves the full pointer in r31; prevents the double lis/addi reload
u8* ptr = (u8*)&globalTable + arg0 * 2;
u8 a = ptr[-0x2a2];
sndFXStartEx(..., a, ...);
u8 b = ptr[-0x2a1];
```
The "wrong" version produces an extra register move before the first access and only
one lis/addi pair instead of two. Use the "correct" version whenever the assembly
shows two separate lis/addi sequences for the same global."""

CODE_RULES = """\
- NEVER use pointer arithmetic with manual offsets. Always define proper structs.
- NEVER use `void*` as an argument or return type. Define typed structs instead.
- All struct field accesses must use `->` or `.` operators.
- When you see `*(type*)((u8*)ptr + 0xNN)`, create a struct with a field at that offset.
- Use `u8 _pad[0xNN];` for unknown fields between known offsets.
- CRITICAL: When accessing fields of an existing struct from the provided definitions, YOU MUST use the EXACT field names provided. DO NOT invent new field names (e.g. do not invent `unk55` if `_55` already exists at offset 0x55).
- Treat the given struct definitions as the ultimate truth. NEVER change the names, types, or offsets of existing struct fields. Only ADD clearly missing fields.
- Check the existing header file for the source file — structs may already be defined.
- ADD PROTOTYPES: If you call a function (like `_OSAllocFromHeap` or `void* memcpy`) that is not in the provided headers, you MUST add its prototype to the [HEADER] or [EXTERNS] section.
- ALWAYS use project types (`u32`, `s16`, `f32`, etc.) instead of standard `long`, `short`, `float`."""

TYPES_REFERENCE = """\
```c
typedef int BOOL;
typedef signed char s8;
typedef signed short s16;
typedef signed long s32;
typedef signed long long s64;
typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned long u32;
typedef unsigned long long u64;
typedef float f32;
typedef double f64;
#define TRUE  1
#define FALSE 0
#define NULL  ((void*)0)
```"""


# INSTRUCTIONS_TEMPLATE = """\
# Implement the function `{func}` in the source file shown above. Replace the existing
# stub with your implementation.

# After implementing:
# 1. Build: `ninja`
# 2. Verify: `python3 tools/feedback_diff.py {func}`
# 3. The ONLY acceptable result is `MATCH!`. A function that compiles is NOT necessarily matched.

# If you need to define new structs, add them to the appropriate header file.
# Keep the code style consistent with the surrounding functions in the source file."""
INSTRUCTIONS_TEMPLATE = """\
Give Instructions on how to Implement the function `{func}` in the source file shown above. Replace the existing
stub with your implementation.

If you need to define new structs, add them to the appropriate header file.
Keep the code style consistent with the surrounding functions in the source file.
If you need to create new variables (for example in a struct) call them something like unk_XX where XX is the byte offset.
Instruct the AI to not rename fields that already exist with the unk_XX format.  the unk_XX format should only be used for unknown variables.

Your instructions will be passed to another AI model to generate the implementation.  Make your instructions clear and concise.
One special Note, if you are defining new Structs, instruct the AI to search for a definition for that struct/variable BEFORE creating a new version.
Don't ask to work on the next function.  Your goal is to only work on the current function.
Instruct the AI to use 'ninja' to verify the whole project builds.  Don't check the match, the user will do that.
"""


# ---------------------------------------------------------------------------
# Context gathering (reuses decomp_helper logic, no AI)
# ---------------------------------------------------------------------------

def find_function(module, max_size, min_size):
    """Find an easy unmatched function from report.json."""
    report_path = os.path.join(ROOT_DIR, "report.json")
    if not os.path.exists(report_path):
        print("Error: report.json not found. Run 'ninja report' first.", file=sys.stderr)
        sys.exit(1)

    with open(report_path, "r") as f:
        data = json.load(f)

    candidates = []
    modules = (module,) if module else ("game", "menus")

    for unit in data.get("units", []):
        unit_name = unit.get("name", "")
        if unit.get("measures", {}).get("matched_code_percent", 0) == 100.0:
            continue

        category = "dol"
        if unit_name.startswith("game/"):
            category = "game"
        elif unit_name.startswith("menus/"):
            category = "menus"
        elif unit_name.startswith("challenge/"):
            category = "challenge"

        if category not in modules:
            continue

        for func in unit.get("functions", []):
            size = int(func.get("size", 0))
            if size < min_size or (max_size and size > max_size):
                continue
            fm = func.get("measures", {})
            if fm.get("matched_code_percent", 0) >= 25.0:
                continue
            candidates.append({
                "name": func.get("name", ""),
                "size": size,
                "unit": unit_name,
                "category": category,
            })

    candidates.sort(key=lambda x: (x["size"], x["name"]))

    # Return first candidate that has a locatable source file and isn't already matched
    for c in candidates:
        info = locate_function(c["name"])
        if not info:
            continue
        
        # Real-time check via objdiff
        match_percent = get_match_percent(c["name"])
        if match_percent is not None and match_percent >= 25.0:
            continue

        # Check if already matched via objdiff (redundant with above but keeps logic safe)
        if match_percent == 100.0:
            continue
            
        return c["name"]

    return None


def get_match_percent(func_name):
    """Get the current match percentage from objdiff."""
    unit = find_unit_for_symbol(func_name)
    if not unit:
        return None
    
    data = run_objdiff(unit, func_name)
    if not data:
        return None
        
    _, right_sym = get_symbol_data(data, func_name)
    if right_sym and "match_percent" in right_sym:
        return float(right_sym["match_percent"])
    return 0.0


def locate_function(func_name):
    """Find source file, module, and address for a function. Returns dict or None."""
    for m in ("", "game", "menus", "challenge"):
        sym_file = os.path.join(CONFIG_BASE, m, "symbols.txt") if m else os.path.join(CONFIG_BASE, "symbols.txt")
        symbols = decomp_helper.parse_symbols(sym_file)
        if func_name in symbols:
            addr = symbols[func_name]["addr"]
            split_file = os.path.join(CONFIG_BASE, m, "splits.txt") if m else os.path.join(CONFIG_BASE, "splits.txt")
            splits = decomp_helper.parse_splits(split_file)
            found_file = decomp_helper.find_file_for_address(splits, addr)
            if found_file:
                return {"module": m, "addr": addr, "file": found_file}
    return None


def get_assembly(func_name, info):
    """Extract the target assembly for a function."""
    module = info["module"]
    rel_path = os.path.splitext(info["file"])[0] + ".s"
    if module:
        asm_path = os.path.join(ROOT_DIR, f"build/GYQE01/{module}/asm", rel_path)
    else:
        asm_path = os.path.join(ROOT_DIR, "build/GYQE01/asm", rel_path)

    asm = decomp_helper.extract_asm(asm_path, func_name)
    if asm:
        return asm

    # Fallback: search asm directory
    search_root = os.path.join(ROOT_DIR, f"build/GYQE01/{module}/asm") if module else os.path.join(ROOT_DIR, "build/GYQE01/asm")
    if os.path.exists(search_root):
        for root, _, files in os.walk(search_root):
            for f in files:
                if f.endswith(".s"):
                    result = decomp_helper.extract_asm(os.path.join(root, f), func_name)
                    if result:
                        return result
    return None


def extract_deps_and_symbols(asm_text):
    """Parse assembly to find bl dependencies and referenced symbols."""
    deps = set()
    syms = set()
    for line in asm_text.splitlines():
        bl_match = re.search(r"\bbl\s+([a-zA-Z0-9_]+)", line)
        if bl_match:
            deps.add(bl_match.group(1))
        sym_match = re.search(r"\b(lbl_[a-zA-Z0-9_]+|g_[a-zA-Z0-9_]+)\b", line)
        if sym_match:
            syms.add(sym_match.group(1))
    return sorted(deps), sorted(syms)


def analyze_function_signature(asm_text):
    """Infer parameter types and return type from assembly patterns.

    Detects clrlwi/extsh/extsb on argument registers near function entry,
    and the same patterns on r3 near blr for return type.

    Returns a dict with:
      'params': list of (reg_index, type_str) sorted by reg index (0=r3, 1=r4, ...)
      'return_type': type_str or None
      'return_from_callee': callee name if return is a saved bl result, else None
    """
    lines = [re.sub(r'/\*.*?\*/', '', l).strip() for l in asm_text.splitlines()]

    # Map clrlwi/extsh/extsb → C type
    def _narrow_type(instr, width_or_none):
        if instr == 'clrlwi':
            if width_or_none == 24:
                return 'u8'
            if width_or_none == 16:
                return 'u16'
        elif instr == 'extsh':
            return 's16'
        elif instr == 'extsb':
            return 's8'
        return None

    # Scan first ~10 non-prologue lines for parameter narrowing ops on r3-r10
    param_types = {}
    for line in lines[:15]:
        # clrlwi rDst, rSrc, N  (narrowing: dst==src, src is arg reg)
        m = re.match(r'clrlwi\s+(r\d+),\s+(r\d+),\s+(\d+)', line)
        if m:
            dst, src, n = m.group(1), m.group(2), int(m.group(3))
            if dst == src:
                reg_n = int(src[1:])
                if 3 <= reg_n <= 10:
                    t = _narrow_type('clrlwi', n)
                    if t:
                        param_types[reg_n - 3] = t
            continue
        # extsh / extsb rDst, rSrc
        m = re.match(r'(extsh|extsb)\s+(r\d+),\s+(r\d+)', line)
        if m:
            instr, dst, src = m.group(1), m.group(2), m.group(3)
            if dst == src:
                reg_n = int(src[1:])
                if 3 <= reg_n <= 10:
                    t = _narrow_type(instr, None)
                    if t:
                        param_types[reg_n - 3] = t

    # Scan last ~10 lines for return type
    return_type = None
    return_from_callee = None
    tail = lines[-12:]

    # Pattern: mr r3, rSAVED where rSAVED was loaded from a bl result
    # First pass: find saved bl results (mr rSAVED, r3 after bl)
    saved_regs = {}  # callee-saved reg -> callee name
    last_bl = None
    for line in lines:
        m = re.match(r'bl\s+(\w+)', line)
        if m:
            last_bl = m.group(1)
            continue
        if last_bl:
            m = re.match(r'mr\s+(r\d+),\s+r3\b', line)
            if m:
                saved_regs[m.group(1)] = last_bl
                last_bl = None

    for line in tail:
        if 'blr' in line:
            break
        # clrlwi r3, r3, N before blr
        m = re.match(r'clrlwi\s+r3,\s+r3,\s+(\d+)', line)
        if m:
            return_type = _narrow_type('clrlwi', int(m.group(1)))
            continue
        # extsh/extsb r3, r3
        m = re.match(r'(extsh|extsb)\s+r3,\s+r3', line)
        if m:
            return_type = _narrow_type(m.group(1), None)
            continue
        # mr r3, rSAVED (returning a saved callee result)
        m = re.match(r'mr\s+r3,\s+(r\d+)', line)
        if m and m.group(1) in saved_regs:
            return_from_callee = saved_regs[m.group(1)]
            if not return_type:
                return_type = '?'  # caller must check callee's return type

    params = sorted(param_types.items())
    return {
        'params': params,
        'return_type': return_type,
        'return_from_callee': return_from_callee,
    }


def detect_indexed_access(asm_text, syms):
    """Detect indexed load/store instructions (lbzx, lhzx, lwzx, lfsx, stbx, etc.)
    to infer array element type for symbols accessed this way.

    Returns dict: symbol_name -> set of type strings (e.g. {'u8'}).
    """
    INDEXED_TYPES = {
        'lbzx': 'u8', 'lbzux': 'u8', 'stbx': 'u8', 'stbux': 'u8',
        'lhzx': 'u16', 'lhzux': 'u16', 'sthx': 'u16', 'sthux': 'u16',
        'lhax': 's16', 'lhaux': 's16',
        'lwzx': 'u32', 'lwzux': 'u32', 'stwx': 'u32', 'stwux': 'u32',
        'lfsx': 'f32', 'lfsux': 'f32', 'stfsx': 'f32', 'stfsux': 'f32',
        'lfdx': 'f64', 'lfdux': 'f64', 'stfdx': 'f64', 'stfdux': 'f64',
    }

    lines = asm_text.splitlines()
    reg_sym = {}   # reg -> symbol name (from lis/addi tracking)
    result = {s: set() for s in syms}

    for line in lines:
        code = re.sub(r'/\*.*?\*/', '', line).strip()

        # lis rN, SYM@ha
        m = re.match(r'lis\s+(r\d+),\s+(\w+)@ha', code)
        if m:
            reg, sym = m.group(1), m.group(2)
            if sym in syms:
                reg_sym[reg] = sym
            continue

        # addi rDst, rSrc, SYM@l
        m = re.match(r'addi\s+(r\d+),\s+(r\d+),\s+(\w+)@l', code)
        if m:
            dst, src, sym = m.group(1), m.group(2), m.group(3)
            if sym in syms and reg_sym.get(src) == sym:
                reg_sym[dst] = sym
                if src != dst:
                    reg_sym.pop(src, None)
            continue

        # mr rDst, rSrc
        m = re.match(r'mr\s+(r\d+),\s+(r\d+)', code)
        if m:
            dst, src = m.group(1), m.group(2)
            if src in reg_sym:
                reg_sym[dst] = reg_sym[src]
            continue

        # Indexed: instr rD, rBase, rIndex  (three-register form, no immediate)
        m = re.match(r'(\w+)\s+(r\d+),\s+(r\d+),\s+(r\d+)', code)
        if m:
            instr, _rd, rb, _ri = m.group(1), m.group(2), m.group(3), m.group(4)
            if instr in INDEXED_TYPES and rb in reg_sym:
                result[reg_sym[rb]].add(INDEXED_TYPES[instr])

    return result


def detect_integer_division(asm_text):
    """Detect compiler-generated signed integer division via reciprocal multiplication.

    CW compiles `x / N` as:
        lis   rM, MAGIC_HI
        addi  rM, rM, MAGIC_LO   (or ori)
        mulhw r0, rM, rX
        srawi r0, r0, K
        srwi  rT, r0, 31
        add   r0, r0, rT

    The magic constant encodes the divisor.  We recover it using:
        divisor = round(2^(32+K) / magic)

    Returns list of (divisor, description_string) for each division found.
    """
    lines = [re.sub(r'/\*.*?\*/', '', l).strip() for l in asm_text.splitlines()]

    magic_regs = {}   # reg -> (magic_value, line_index)
    results = []
    seen_divisors = set()

    for i, line in enumerate(lines):
        # lis rN, HI
        m = re.match(r'lis\s+(r\d+),\s+(0x[0-9A-Fa-f]+|-?\d+)', line)
        if m:
            reg, hi_s = m.group(1), m.group(2)
            hi = int(hi_s, 16) if hi_s.startswith('0x') else int(hi_s)
            magic_regs[reg] = (hi << 16, i)
            continue

        # addi rDst, rSrc, LO  (finalising the magic constant)
        m = re.match(r'addi\s+(r\d+),\s+(r\d+),\s+(0x[0-9A-Fa-f]+|-?\d+)', line)
        if m:
            dst, src, lo_s = m.group(1), m.group(2), m.group(3)
            if src in magic_regs:
                lo = int(lo_s, 16) if lo_s.startswith('0x') else int(lo_s)
                # addi sign-extends 16-bit immediate
                if lo > 0x7FFF:
                    lo -= 0x10000
                magic_val = (magic_regs[src][0] + lo) & 0xFFFFFFFF
                # sign-extend 32-bit
                if magic_val >= 0x80000000:
                    magic_val -= 0x100000000
                magic_regs[dst] = (magic_val, i)
            continue

        # mulhw r0, rMagic, rX
        m = re.match(r'mulhw\s+(\w+),\s+(r\d+),\s+\w+', line)
        if m:
            _dst, magic_reg = m.group(1), m.group(2)
            if magic_reg not in magic_regs:
                continue
            magic_val, _ = magic_regs[magic_reg]
            if magic_val == 0:
                continue

            # Look ahead for srawi to get shift amount K
            shift_k = None
            for j in range(i + 1, min(i + 6, len(lines))):
                sm = re.match(r'srawi\s+\w+,\s+\w+,\s+(\d+)', lines[j])
                if sm:
                    shift_k = int(sm.group(1))
                    break

            if shift_k is None:
                continue

            # Recover divisor: divisor ≈ 2^(32+K) / magic  (for positive magic)
            # For negative magic (magic < 0), divisor = -round(2^(32+K) / magic)
            try:
                power = (1 << (32 + shift_k))
                if magic_val > 0:
                    divisor = round(power / magic_val)
                else:
                    divisor = -round(power / (-magic_val))
            except Exception:
                continue

            if divisor < 2 or divisor in seen_divisors:
                continue
            seen_divisors.add(divisor)

            magic_hex = magic_val & 0xFFFFFFFF
            results.append((
                divisor,
                f"magic constant `0x{magic_hex:08X}` + `srawi {shift_k}` "
                f"→ compiler-generated division by **{divisor}** — write `value / {divisor}` in C"
            ))

    return results


def load_symbol_db(module=None):
    """Load symbols from symbols.txt for the given module (or DOL if module is falsy).

    Returns a dict: symbol_name -> {addr, section, type, size}.
    """
    if module:
        sym_file = os.path.join(CONFIG_BASE, module, "symbols.txt")
    else:
        sym_file = os.path.join(CONFIG_BASE, "symbols.txt")

    db = {}
    if not os.path.exists(sym_file):
        return db
    with open(sym_file, "r") as f:
        for line in f:
            # name = .section:0xADDR; // type:TYPE size:0xSIZE ...
            m = re.match(
                r'(\w+)\s*=\s*([\.\w]+):0x([0-9A-Fa-f]+)\s*;(?:\s*//\s*(.*))?', line
            )
            if not m:
                continue
            name, section, addr_hex, comment = m.groups()
            entry = {"addr": int(addr_hex, 16), "section": section, "type": None, "size": None}
            if comment:
                tm = re.search(r'type:(\S+)', comment)
                sm = re.search(r'size:0x([0-9A-Fa-f]+)', comment)
                if tm:
                    entry["type"] = tm.group(1)
                if sm:
                    entry["size"] = int(sm.group(1), 16)
            db[name] = entry
    return db


def detect_strides(asm_text, sym_db):
    """Scan assembly for mulli instructions and pair strides with nearby base symbols.

    Returns a dict: symbol_name -> set of integer strides observed.
    """
    lines = asm_text.splitlines()
    strides = {}  # sym -> set of stride ints

    for i, line in enumerate(lines):
        mulli_m = re.search(r'\bmulli\s+\w+,\s*\w+,\s*(0x[0-9A-Fa-f]+|\d+)', line)
        if not mulli_m:
            continue
        raw = mulli_m.group(1)
        stride = int(raw, 16) if raw.startswith("0x") else int(raw)
        if stride < 2:
            continue

        # Look back up to 8 lines for the most recent lbl_ symbol reference
        window = lines[max(0, i - 8): i + 1]
        for wline in reversed(window):
            sym_m = re.search(r'\b(lbl_[0-9A-Fa-f]+)\b', wline)
            if sym_m:
                sym = sym_m.group(1)
                strides.setdefault(sym, set()).add(stride)
                break

    return strides


def extract_symbol_offsets(asm_text, syms):
    """Track register→symbol assignments and collect load/store offsets per symbol.

    Follows lis/addi pairs to know which register holds a symbol's base address,
    then records every immediate offset used in a load/store on that register.
    Invalidates a register when it is self-incremented (pointer advance).

    Distinguishes two access patterns:
      lis rN, SYM@ha  +  addi rDst, rN, SYM@l   → &SYM  (array/struct-in-place)
      lis rN, SYM@ha  +  lwz  rDst, SYM@l(rN)   → *SYM  (pointer dereference)

    Returns (offsets_dict, pointer_deref_syms):
      offsets_dict: symbol_name -> set of int offsets accessed on the symbol itself
      pointer_deref_syms: set of symbol names accessed via pointer dereference (lwz @l)
    """
    lines = asm_text.splitlines()
    reg_sym = {}  # reg -> symbol name
    sym_offsets = {s: set() for s in syms}
    pointer_deref_syms = set()

    for line in lines:
        code = re.sub(r'/\*.*?\*/', '', line).strip()

        # lis rN, SYM@ha  →  tentatively associate rN with SYM
        m = re.match(r'lis\s+(r\d+),\s+(\w+)@ha', code)
        if m:
            reg, sym = m.group(1), m.group(2)
            if sym in syms:
                reg_sym[reg] = sym
            continue

        # addi rDst, rSrc, SYM@l  →  confirm rDst holds &SYM (address, not value)
        m = re.match(r'addi\s+(r\d+),\s+(r\d+),\s+(\w+)@l', code)
        if m:
            dst, src, sym = m.group(1), m.group(2), m.group(3)
            if sym in syms and reg_sym.get(src) == sym:
                reg_sym[dst] = sym
                if src != dst:
                    reg_sym.pop(src, None)
            continue

        # lwz rDst, SYM@l(rBase)  →  *SYM (pointer-global dereference pattern)
        # The symbol holds a pointer; rDst gets the pointed-to value.
        # Do NOT propagate SYM tracking to rDst — field accesses on rDst belong to
        # the inner type, not to SYM itself.
        m = re.match(r'lwz\s+(r\d+),\s+(\w+)@l\((r\d+)\)', code)
        if m:
            dst, sym, base = m.group(1), m.group(2), m.group(3)
            if sym in syms and reg_sym.get(base) == sym:
                pointer_deref_syms.add(sym)
                reg_sym.pop(base, None)  # consume the lis association
                # rDst now holds the inner pointer value — clear any old tracking
                reg_sym.pop(dst, None)
            continue

        # mr rDst, rSrc  →  propagate symbol association
        m = re.match(r'mr\s+(r\d+),\s+(r\d+)', code)
        if m:
            dst, src = m.group(1), m.group(2)
            if src in reg_sym:
                reg_sym[dst] = reg_sym[src]
            continue

        # addi rDst, rDst, imm (no @l)  →  pointer shifted, invalidate
        m = re.match(r'addi\s+(r\d+),\s+(r\d+),\s+(0x[0-9A-Fa-f]+|-?\d+)\s*$', code)
        if m:
            dst, src = m.group(1), m.group(2)
            if dst == src and dst in reg_sym:
                reg_sym.pop(dst)
            continue

        # Load/store: instr first_reg, offset(base_reg)
        m = re.search(r'\b([ls]\w+)\s+(r\d+),\s*(0x[0-9A-Fa-f]+|-?\d+)\s*\((\w+)\)', code)
        if m:
            instr, first_reg, offset_str, base_reg = m.groups()
            if base_reg in reg_sym:
                sym = reg_sym[base_reg]
                try:
                    offset = int(offset_str, 16) if offset_str.startswith('0x') else int(offset_str)
                except ValueError:
                    continue

                # lwz at offset 0: pointer dereference — propagate tracking to dst,
                # don't record offset 0 as a struct field access.
                if instr in ('lwz', 'lwzu') and offset == 0 and instr[0] == 'l':
                    reg_sym[first_reg] = sym
                elif offset >= 0:
                    sym_offsets[sym].add(offset)

    return sym_offsets, pointer_deref_syms


def find_declaration(symbol, include_dir):
    """Search headers for the extern declaration of a symbol.

    Returns (filepath, declaration_line, type_name) or (None, None, None).
    """
    try:
        result = subprocess.run(
            ["grep", "-rn", rf"\b{symbol}\b", include_dir],
            capture_output=True, text=True, timeout=5,
        )
        for line in result.stdout.splitlines():
            parts = line.split(":", 2)
            if len(parts) < 3:
                continue
            filepath, _, content = parts
            stripped = content.strip()
            if "extern" in stripped and symbol in stripped:
                type_match = re.match(
                    rf'extern\s+([\w\s\*]+?)\s*\b{re.escape(symbol)}\b[\s\[\];]',
                    stripped,
                )
                type_name = type_match.group(1).strip() if type_match else None
                # Strip pointer qualifiers so "Foo*" resolves to struct "Foo"
                is_pointer = type_name and type_name.endswith('*')
                if type_name:
                    type_name = type_name.rstrip('*').strip()
                return filepath, stripped, type_name, is_pointer
    except Exception:
        pass
    return None, None, None, False


def extract_struct_block(content, type_name):
    """Extract the typedef struct { ... } TypeName; block from file content.

    Handles nested braces and returns just the text of the relevant struct,
    scoped to avoid cross-contamination from other structs in the same file.
    """
    # Find the closing line '} TypeName;' to anchor the end
    end_pat = re.compile(rf'\}}\s*{re.escape(type_name)}\s*;')
    end_match = end_pat.search(content)
    if not end_match:
        return None

    # Walk backwards from the end to find the matching opening brace
    before = content[:end_match.end()]
    depth = 0
    start_idx = None
    for i in range(len(before) - 1, -1, -1):
        ch = before[i]
        if ch == '}':
            depth += 1
        elif ch == '{':
            depth -= 1
            if depth == 0:
                start_idx = i
                break

    if start_idx is None:
        return None
    return content[start_idx:end_match.end()]


def find_fields_at_offsets(type_name, offsets, include_dir):
    """Extract struct field lines at specific byte offsets for a given type.

    Searches headers for a file that defines 'typedef struct { ... } TypeName;',
    then greps for offset comments like /*0x1D64*/ to find the relevant fields.

    Returns a list of annotated field strings.
    """
    if not type_name or not offsets:
        return []

    try:
        result = subprocess.run(
            ["grep", "-rln", rf"\b{type_name}\b", include_dir],
            capture_output=True, text=True, timeout=5,
        )
        candidate_files = result.stdout.splitlines()
    except Exception:
        return []

    for filepath in candidate_files:
        try:
            with open(filepath) as f:
                content = f.read()
        except Exception:
            continue

        # Extract just the typedef struct block for this type
        struct_block = extract_struct_block(content, type_name)
        if not struct_block:
            continue

        struct_lines = struct_block.splitlines()
        CONTEXT = 3  # lines before/after to show for layout awareness

        # Pre-parse the offset value commented on each struct line (for proximity search)
        def line_offset(line):
            m = re.search(r'/\*\s*0x([0-9A-Fa-f]+)\s*\*/', line)
            return int(m.group(1), 16) if m else None

        line_offsets = [line_offset(l) for l in struct_lines]

        fields = []
        emitted_lines = set()  # deduplicate context lines globally across all offsets

        for offset in sorted(offsets):
            hex_variants = {f"{offset:X}", f"{offset:x}", f"{offset:02X}", f"{offset:02x}",
                            f"{offset:04X}", f"{offset:04x}"}
            alts = "|".join(rf'0x{h}' for h in hex_variants)
            pat = rf'/\*\s*(?:{alts})\s*\*/'

            # Find lines that directly match this offset via comment annotation
            match_indices = [i for i, l in enumerate(struct_lines)
                             if re.search(pat, l, re.IGNORECASE)]

            # Fallback: match via field name convention (e.g. field_0x479, _479, unk479)
            if not match_indices:
                name_alts = "|".join(rf'(?:field_|unk_?|_)0x{h}' for h in hex_variants)
                name_pat = rf'\b(?:{name_alts})\b'
                match_indices = [i for i, l in enumerate(struct_lines)
                                 if re.search(name_pat, l, re.IGNORECASE)]

            if not match_indices:
                # Offset not found — probably inside a padding block.
                # Find the nearest surrounding annotated lines as pivots.
                before = [i for i, o in enumerate(line_offsets) if o is not None and o <= offset]
                after  = [i for i, o in enumerate(line_offsets) if o is not None and o > offset]
                pivot_indices = (before[-1:] if before else []) + (after[:1] if after else [])
                if not pivot_indices:
                    # Struct has no annotated lines at all — emit offset as needing definition
                    fields.append(f"  +0x{offset:X}: (not yet defined in struct — add a field here)")
                    continue
                fields.append(f"  +0x{offset:X}: (not a declared field — falls inside a padding block):")
            else:
                pivot_indices = match_indices
                fields.append(f"  +0x{offset:X}:")

            # Emit context window, deduplicating lines already shown by a prior offset
            for pivot in pivot_indices:
                lo = max(0, pivot - CONTEXT)
                hi = min(len(struct_lines), pivot + CONTEXT + 1)
                for i in range(lo, hi):
                    line_text = struct_lines[i].strip()
                    # Skip struct closing brace lines (they add no field info)
                    if re.match(r'^\}', line_text):
                        continue
                    if line_text and line_text not in emitted_lines:
                        marker = " ◄" if i == pivot and match_indices else ""
                        fields.append(f"    {line_text}{marker}")
                        emitted_lines.add(line_text)

        return fields

    return []


def annotate_referenced_symbols(syms, asm_text, module=None, indexed_types=None):
    """Build an annotated symbol context section for the prompt.

    For each symbol:
      - Looks up size/type from symbols.txt
      - Detects mulli strides to infer array element size
      - Detects indexed loads (lbzx etc.) to infer array element type
      - Notes if the symbol is undeclared (not in any header), with suggested extern
    Returns a markdown string, or "" if nothing useful.
    """
    if not syms:
        return ""

    if indexed_types is None:
        indexed_types = {}

    # DOL symbols (lbl_80XXXXXX) live in the DOL symbol db; REL symbols in module db
    dol_db = load_symbol_db(module=None)
    mod_db = load_symbol_db(module=module) if module else {}
    strides = detect_strides(asm_text, {**dol_db, **mod_db})
    sym_offsets, pointer_deref_syms = extract_symbol_offsets(asm_text, syms)

    include_dir = os.path.join(ROOT_DIR, "include")

    lines = ["## Referenced Symbols\n"]
    for sym in syms:
        info = dol_db.get(sym) or mod_db.get(sym)
        lines.append(f"- `{sym}`")

        if info:
            addr_str = f"0x{info['addr']:08X}" if info.get("addr") else "?"
            size_str = f"0x{info['size']:X}" if info.get("size") else "unknown"
            sec_str = info.get("section", "?")
            type_str = info.get("type", "?")
            lines.append(f"  - Section: {sec_str}, Address: {addr_str}, "
                         f"Type: {type_str}, Size: {size_str} bytes")

            # Stride hint
            if sym in strides:
                for stride in sorted(strides[sym]):
                    size = info.get("size")
                    hint = f"  - ARRAY HINT: `mulli` stride 0x{stride:X} detected"
                    if size and stride > 0:
                        count = size // stride
                        hint += (f" → array of ~{count} elements × 0x{stride:X} bytes. "
                                 f"Define a struct of size 0x{stride:X} and use array/field access.")
                    else:
                        hint += f" → define a struct of size 0x{stride:X} bytes."
                    lines.append(hint)
        else:
            # Symbol not in any symbols.txt — might be a REL local label
            lines.append(f"  - (address not found in symbols.txt)")

        # Find declaration and extract relevant struct fields
        filepath, decl_line, type_name, is_pointer = find_declaration(sym, include_dir)
        if decl_line:
            rel_path = os.path.relpath(filepath, ROOT_DIR) if filepath else "?"
            lines.append(f"  - Declared as: `{decl_line}` (in `{rel_path}`)")

            if sym in pointer_deref_syms:
                lines.append(
                    f"  - ⚠ POINTER-GLOBAL pattern: assembly uses `lwz` through `{sym}` "
                    f"(not `addi`) — the symbol is a struct whose first field (offset 0x0) "
                    f"is a pointer to an array. Access elements via `{sym}.field_0x0[index]`, "
                    f"NOT `{sym}[index]`. Field offsets below belong to the pointed-to element "
                    f"type, not to `{type_name}` itself."
                )

            offsets = sym_offsets.get(sym, set())
            if type_name and offsets:
                field_lines = find_fields_at_offsets(type_name, offsets, include_dir)
                if field_lines:
                    label = (f"  - Accessed fields of `{type_name}` (via pointer `*{sym}`):"
                             if is_pointer else f"  - Accessed fields of `{type_name}`:")
                    lines.append(label)
                    lines.extend(field_lines)
        else:
            # Build a suggested extern declaration using indexed access type + size
            elem_types = indexed_types.get(sym, set())
            sym_info = dol_db.get(sym) or mod_db.get(sym)
            if elem_types:
                # If all indexed accesses agree on one type, use it; else show all
                elem_type = next(iter(elem_types)) if len(elem_types) == 1 else "/".join(sorted(elem_types))
                if sym_info and sym_info.get("size") and len(elem_types) == 1:
                    size_bytes = sym_info["size"]
                    # Deduce element size from type
                    type_sizes = {'u8': 1, 's8': 1, 'u16': 2, 's16': 2,
                                  'u32': 4, 's32': 4, 'f32': 4, 'f64': 8}
                    esz = type_sizes.get(elem_type, 0)
                    if esz > 0:
                        count = size_bytes // esz
                        suggested = f"extern {elem_type} {sym}[{count}];"
                    else:
                        suggested = f"extern {elem_type} {sym}[];"
                else:
                    suggested = f"extern {elem_type} {sym}[];"
                lines.append(
                    f"  - **NOT declared in any header** — "
                    f"accessed via indexed load/store (`{elem_type}` element type); "
                    f"suggested: `{suggested}`"
                )
            else:
                lines.append(f"  - **NOT declared in any header** — add an extern declaration before use")

    return "\n".join(lines)


def annotate_ghidra_addresses(ghidra_text, module=None):
    """Replace Ghidra's INT_/DAT_ absolute addresses with symbolic annotations.

    When Ghidra shows `&INT_803617e4`, resolve that address against known symbols
    and annotate it as e.g. `/* lbl_803616CC + 0x118 */ &INT_803617e4`.
    Returns the annotated string.
    """
    if not ghidra_text:
        return ghidra_text

    dol_db = load_symbol_db(module=None)
    # Build a sorted list of (addr, name, size) for range lookup
    symbol_ranges = sorted(
        [(v["addr"], k, v.get("size") or 0)
         for k, v in dol_db.items() if v.get("addr") is not None],
        key=lambda x: x[0],
    )

    def _resolve_addr(addr_int):
        """Find which symbol contains addr_int and return 'sym + 0xOFFSET'."""
        for sym_addr, sym_name, sym_size in reversed(symbol_ranges):
            if sym_addr <= addr_int:
                offset = addr_int - sym_addr
                # Accept if within the symbol's size, or within a reasonable 0x200 window
                limit = sym_size if sym_size else 0x200
                if offset <= limit:
                    if offset == 0:
                        return sym_name
                    return f"{sym_name} + 0x{offset:X}"
        return None

    def _replace_addr(m):
        raw = m.group(0)
        hex_str = m.group(1)
        try:
            addr_int = int(hex_str, 16)
        except ValueError:
            return raw
        resolved = _resolve_addr(addr_int)
        if resolved and resolved != raw:
            return f"{raw}  /* {resolved} */"
        return raw

    # Match INT_XXXXXXXX, DAT_XXXXXXXX, PTR_XXXXXXXX, and raw 0x80XXXXXX addresses
    annotated = re.sub(
        r'\b(?:INT|DAT|PTR|FUN|LAB|SUB)_([0-9A-Fa-f]{8})\b',
        _replace_addr,
        ghidra_text,
    )
    # Also match standalone 0x80XXXXXX literals in Ghidra context
    def _replace_literal(m):
        raw = m.group(0)
        hex_str = m.group(1)
        try:
            addr_int = int(hex_str, 16)
        except ValueError:
            return raw
        if addr_int < 0x80000000:
            return raw
        resolved = _resolve_addr(addr_int)
        if resolved and resolved != raw:
            return f"{raw}  /* {resolved} */"
        return raw

    annotated = re.sub(r'\b0x(8[0-9A-Fa-f]{7})\b', _replace_literal, annotated)
    return annotated


def find_signature(symbol):
    """Search include/ for a function signature."""
    include_dir = os.path.join(ROOT_DIR, "include")
    try:
        result = subprocess.run(
            ["grep", "-rE", rf"\b{re.escape(symbol)}\s*\(", include_dir],
            capture_output=True, text=True,
        )
        if result.returncode == 0:
            for line in result.stdout.splitlines():
                if ";" in line or "{" in line:
                    return line.strip()
    except Exception:
        pass
    return None


def read_source_file(info):
    """Read the source .c file content."""
    src_path = os.path.join(ROOT_DIR, "src", info["file"])
    if os.path.exists(src_path):
        with open(src_path, "r") as f:
            return src_path, f.read()
    return src_path, None


def read_header_file(info):
    """Read the primary header for the source file."""
    # Source file is e.g. "game/rep_1838.c", header is "include/game/rep_1838.h"
    header_rel = os.path.splitext(info["file"])[0] + ".h"
    header_path = os.path.join(ROOT_DIR, "include", header_rel)
    if os.path.exists(header_path):
        with open(header_path, "r") as f:
            return header_path, f.read()
    return header_path, None


def run_feedback(func_name):
    """Run feedback_diff.py and return stdout."""
    try:
        result = subprocess.run(
            ["python3", os.path.join(script_dir, "feedback_diff.py"), func_name],
            capture_output=True, text=True, cwd=ROOT_DIR,
        )
        return result.stdout
    except Exception:
        return None


def run_m2c(func_name):
    """Run m2c_helper.py and return stdout."""
    try:
        result = subprocess.run(
            ["python3", os.path.join(script_dir, "m2c_helper.py"), func_name],
            capture_output=True, text=True, cwd=ROOT_DIR,
        )
        if result.returncode == 0:
            lines = result.stdout.splitlines()
            # Filter out decompctx logging
            filtered = [l for l in lines if not l.startswith("Processing file")]
            return "\n".join(filtered)
    except Exception:
        pass
    return None


def run_ghidra_decomp(func_name, addr=None, module=None):
    """Extract Ghidra decompilation from in_game.c."""
    in_game_c = os.path.join(ROOT_DIR, "in_game.c")
    return extract_ghidra_decomp(func_name, in_game_c, addr=addr, module=module)


# ---------------------------------------------------------------------------
# Prompt assembly
# ---------------------------------------------------------------------------

def extract_m2c_prototypes(m2c_output):
    """Extract function prototypes that m2c placed at the top of its output.

    m2c emits lines like:
        ? FuncName(type, type, ...);  /* extern */
    Returns dict: func_name -> prototype_string.
    """
    protos = {}
    if not m2c_output:
        return protos
    for line in m2c_output.splitlines():
        # Match lines that look like a prototype with /* extern */ comment
        m = re.match(r'(.+?\b(\w+)\s*\([^)]*\)\s*;)\s*/\*\s*extern\s*\*/', line.strip())
        if m:
            protos[m.group(2)] = m.group(1).strip()
    return protos


def build_prompt(func_name, info, asm_text, deps, syms, src_path, src_content,
                 header_path, header_content, feedback, m2c_output, ghidra_output):
    """Assemble the complete prompt."""
    sections = []

    sections.append(f"# Decompile: `{func_name}`\n")

    # Background
    sections.append("## Project Background\n")
    sections.append(BACKGROUND)

    # Types
    sections.append("\n## Core Types\n")
    sections.append(TYPES_REFERENCE)

    # Compiler patterns
    sections.append("\n## Compiler Behavior Patterns (Metrowerks CodeWarrior / PowerPC)\n")
    sections.append(COMPILER_PATTERNS)

    # Code rules
    sections.append("\n## Code Quality Rules\n")
    sections.append(CODE_RULES)

    # Function info
    sections.append(f"\n## Function Info\n")
    sections.append(f"- **Name**: `{func_name}`")
    sections.append(f"- **Address**: `{hex(info['addr'])}`")
    sections.append(f"- **Module**: `{info['module'] or 'main'}`")
    sections.append(f"- **Source file**: `src/{info['file']}`")

    # Assembly
    sections.append(f"\n## Target Assembly\n")
    sections.append(f"```asm\n{asm_text.strip()}\n```")

    # --- Assembly analysis hints ---
    sig_hints = analyze_function_signature(asm_text)
    div_hints = detect_integer_division(asm_text)
    indexed_types = detect_indexed_access(asm_text, set(syms))

    hint_lines = []

    # Parameter type hints
    if sig_hints['params']:
        for idx, ptype in sig_hints['params']:
            reg = f"r{idx + 3}"
            hint_lines.append(
                f"- **Parameter {idx} ({reg})** narrows to `{ptype}` at function entry "
                f"— declare as `{ptype}` in the function signature."
            )

    # Return type hint
    if sig_hints['return_type'] and sig_hints['return_type'] != '?':
        hint_lines.append(
            f"- **Return type**: assembly narrows/extends `r3` before `blr` → return type is `{sig_hints['return_type']}`."
        )
    elif sig_hints['return_from_callee']:
        hint_lines.append(
            f"- **Return type**: function saves r3 from `{sig_hints['return_from_callee']}` and returns it — "
            f"check `{sig_hints['return_from_callee']}`'s return type and use it here."
        )

    # Integer division hints
    for _divisor, desc in div_hints:
        hint_lines.append(f"- **Integer division**: {desc}.")

    # Signature mismatch warning
    if (sig_hints['params'] or sig_hints['return_type']) and header_content:
        # Find the declared signature in the header
        decl_pat = re.compile(
            rf'(\w[\w\s\*]*?)\s+\b{re.escape(func_name)}\s*\(([^)]*)\)\s*;'
        )
        hm = decl_pat.search(header_content)
        if hm:
            declared_ret = hm.group(1).strip()
            declared_params = hm.group(2).strip()
            inferred_ret = sig_hints['return_type']
            mismatches = []
            if inferred_ret and inferred_ret != '?' and declared_ret == 'void':
                mismatches.append(
                    f"return type is declared `void` but assembly implies `{inferred_ret}`"
                )
            if sig_hints['params'] and (declared_params == 'void' or declared_params == ''):
                mismatches.append(
                    f"function is declared with no parameters but assembly implies "
                    + ", ".join(f"arg{i}:{t}" for i, t in sig_hints['params'])
                )
            if mismatches:
                hint_lines.append(
                    f"\n> **WARNING — signature mismatch**: "
                    + "; ".join(mismatches) + ". "
                    f"Update the signature in **both** the header (`include/...`) and source file."
                )

    if hint_lines:
        sections.append(f"\n## Assembly Analysis Hints\n")
        sections.append("\n".join(hint_lines))

    # Dependencies
    m2c_protos = extract_m2c_prototypes(m2c_output)
    if deps:
        sections.append(f"\n## Dependencies (bl calls)\n")
        for dep in deps:
            sig = find_signature(dep)
            if sig:
                sections.append(f"- `{dep}`: `{sig}`")
            elif dep in m2c_protos:
                sections.append(f"- `{dep}` (not in headers; m2c suggests: `{m2c_protos[dep]}`)")
            else:
                sections.append(f"- `{dep}` (signature not found in headers)")

    # Referenced symbols (annotated with size/type/stride hints + indexed access types)
    if syms:
        sym_section = annotate_referenced_symbols(
            syms, asm_text, module=info.get("module"), indexed_types=indexed_types
        )
        sections.append(f"\n{sym_section}")

    # Current feedback
    if feedback and "MATCH!" not in feedback:
        sections.append(f"\n## Current Diff (compiled vs target)\n")
        sections.append(f"```\n{feedback.strip()}\n```")

    # m2c approximate decomp
    if m2c_output:
        sections.append(f"\n## Approximate Decompilation (from m2c)\n")
        sections.append(f"```c\n{m2c_output.strip()}\n```")

        # Callout: M2C_ERROR means the function signature is wrong
        errors = re.findall(r'M2C_ERROR\(/\* Read from unset register \$(r\d+) \*/\)', m2c_output)
        if errors:
            regs = ", ".join(sorted(set(errors)))
            sections.append(
                f"\n> **WARNING — wrong function signature**: m2c found unset register(s) `{regs}`. "
                f"This means the function has parameter(s) that are not declared in the current signature. "
                f"The calling convention passes arguments in r3, r4, r5, ... in order — "
                f"add the missing parameter(s) to the function signature in **both** the header and source file "
                f"before implementing the function body."
            )

    # Ghidra decompilation (with address annotations)
    if ghidra_output:
        annotated_ghidra = annotate_ghidra_addresses(ghidra_output, module=info.get("module"))
        sections.append(f"\n## Ghidra Decompilation (from in_game.c)\n")
        sections.append(f"```c\n{annotated_ghidra.strip()}\n```")

    # Header file
    if header_content:
        rel = os.path.relpath(header_path, ROOT_DIR)
        sections.append(f"\n## Header: `{rel}`\n")
        sections.append(f"```c\n{header_content.strip()}\n```")

    # Source file
    if src_content:
        rel = os.path.relpath(src_path, ROOT_DIR)
        sections.append(f"\n## Source File: `{rel}`\n")
        sections.append(f"```c\n{src_content.strip()}\n```")

    # Instructions
    sections.append(f"\n## Instructions\n")
    sections.append(INSTRUCTIONS_TEMPLATE.format(func=func_name))

    return "\n".join(sections)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate an AI prompt for decompiling a function."
    )
    parser.add_argument(
        "function", nargs="?", default=None,
        help="Function name to decompile (auto-selects if omitted)",
    )
    parser.add_argument("--module", default=None, help="Filter by module (game, menus)")
    parser.add_argument("--max-size", type=int, default=None, help="Max function size in bytes")
    parser.add_argument("--min-size", type=int, default=8, help="Min function size (default: 8)")
    parser.add_argument("--output", "-o", default=None, help="Write prompt to file instead of stdout")
    args = parser.parse_args()

    # 1. Find or validate function
    if args.function:
        func_name = args.function
    else:
        print("Searching for an unmatched function...", file=sys.stderr)
        func_name = find_function(args.module, args.max_size, args.min_size)
        if not func_name:
            print("No suitable unmatched function found.", file=sys.stderr)
            sys.exit(1)
        print(f"Selected: {func_name}", file=sys.stderr)

    # 2. Locate function
    info = locate_function(func_name)
    if not info:
        print(f"Error: Could not locate {func_name} in symbols.", file=sys.stderr)
        sys.exit(1)

    # 3. Get assembly
    asm_text = get_assembly(func_name, info)
    if not asm_text:
        print(f"Error: Could not extract assembly for {func_name}.", file=sys.stderr)
        sys.exit(1)

    # 4. Extract deps and symbols from assembly
    deps, syms = extract_deps_and_symbols(asm_text)

    src_path, src_content = read_source_file(info)
    header_path, header_content = read_header_file(info)

    # 6. Get current feedback
    feedback = run_feedback(func_name)

    # 7. Run m2c and Ghidra extraction
    m2c_output = run_m2c(func_name)
    ghidra_output = run_ghidra_decomp(func_name, addr=info.get("addr"), module=info.get("module"))

    # 8. Build prompt
    prompt = build_prompt(
        func_name, info, asm_text, deps, syms,
        src_path, src_content, header_path, header_content, feedback, 
        m2c_output, ghidra_output,
    )

    # 8. Output
    if args.output:
        with open(args.output, "w") as f:
            f.write(prompt)
        print(f"Prompt written to {args.output}", file=sys.stderr)
    else:
        print(prompt)


if __name__ == "__main__":
    main()
